plugins {
    id 'java'
    id 'maven-publish'
    id 'com.enonic.xp.app'
    id 'com.github.node-gradle.node' version "7.1.0"
}

group = 'com.github.bouvet-apps'

compileJava.options.encoding = "UTF-8"

xp {
  version = xpVersion
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = "${group}"
            artifactId = "${projectName}"
            version = "${version}"

            from components.java
        }
    }
}

task npmBuild(type: NpmTask,
        group: 'node',
        dependsOn: 'npmInstall',
        description: 'Transpile ES6 files'
    ) {
    args = ['run', 'build']

    inputs.dir 'src/main/resources'
    outputs.dir "$buildDir/resources/main"
}
rootProject.tasks.getByName("processResources").dependsOn npmBuild

dependencies {
    implementation xplibs.api.core
    implementation xplibs.api.portal
    include xplibs.admin
    include xplibs.content
    include xplibs.portal
    include xplibs.auth
    include xplibs.context
    include xplibs.i18n
    include "com.enonic.lib:lib-util:3.1.1"
}

repositories {
    mavenLocal()
    mavenCentral()
    xp.enonicRepo()
    maven {
        url 'https://repo.enonic.com/public'
    }
}

node {
    version = '16.20.2'
    npmVersion = '8.19.4'
    download = true
}

wrapper {
    gradleVersion = '9.5.0'
    distributionType = Wrapper.DistributionType.BIN
}
